[Bindable]
public var languageArray:Object;

public function languageInit(str:String):void{
	
	if (str == "ENGLISH"){
		languageArray = {
			"Add Alert": "Add Alert",
		  	"Add new note":"Add new note",
		  	"Add new visit":"Add new visit",
		  	"Add new allergy":"Add new allergy",
		  	"Add new vaccination":"Add new vaccination",
		  	"Add New Patient":"Add New Patient",
			"Add Patient": "Add Patient",
			"Address": "Address",
			"Administration": "Administration",
			"Alert Date": "Alert Date",
			"Alert List": "Alert List",
			"Alert Note": "Alert Note",
			"Alerts": "Alerts",
			"Allergies":"Allergies",
			"Allergy List": "Allergy List",
			"Allergy Name": "Allergy Name",
			"Arrival Date": "Arrival Date",
			"City": "City",
			"Conditions":"Conditions",
			"Condition List":"Condition List",
			"Condition Name":"Condition Name",
			"Confirm Password": "Confirm Password",
			"Create Account": "Create a New Account",
			"Create": "Create",
			"Date of Birth": "Date of Birth",
		  	"Date Administered":"Date Administered",
		  	"Date Observed":"Date Observed",		  
		  	"Date Seen":"Date Seen",
		  	"Delete":"Delete",
			"Emergency Contact Name": "Emergency Contact Name",
			"Emergency Contact Relationship": "Emergency Contact Relationship",
			"Father First Name": "Father First Name",
			"Father Last Name": "Father Last Name",
			"Female": "Female",
			"First Name": "First Name",
		  	"Follow Up":"Follow Up",
		  	"Follow Up?":"Follow Up?",
			"Gender": "Gender",
		  	"General Information":"General Information",
			"Hello": "Bonjour",
			"Last Name": "Last Name",
			"Login": "Login",
			"Logout": "Logout",
			"Male": "Male",
			"Medical Record ID": "Medical Record ID",
			"Middle Name": "Middle Name",
			"Mother First Name": "Mother First Name",
			"Mother Last Name": "Mother Last Name",
		  	"Name":"Name",
		  	"Notes":"Notes",
			"Password": "Password",
		  	"Patient Active":"Patient Active",
		  	"Patient ID":"Patient ID",
		  	"Patient": "Patient",
			"Patient List": "Patient List",
			"Patient Name": "Patient Name",
			"Patient Remarks": "Patient Remarks",
			"Patients": "Patients",
		  	"Reason":"Reason",
		  	"Search by Allergy Name": "Search by Allergy Name",
		  	"Search by Condition Name": "Search by Condition Name",
			"Search by Patient Name": "Search by Patient Name",
			"Search by Vaccination Name": "Search by Vaccination Name",
			"Search": "Search",
			"Severity":"Severity",
			"Show All": "Show All",
			"State": "State",
			"Telephone": "Telephone",
			"Username":"Username",
			"Vaccination List":"Vaccination List",
			"Vaccination Name":"Vaccination Name",
			"Vaccinations":"Vaccinations",
			"Visit Date":"Visit Date",
		    "View":"View",
			"Zip": "Zip"
			
		}
	}
	if(str == "FRENCH"){
		languageArray = {
		  "Add Alert": "Ajouter Alerte",
		  "Add new note":"Ajouter Nouvelle Remarques",
		  "Add new visit":"Ajouter Nouvelle Visite",
		  "Add new allergy":"Ajouter Nouvelle Allergie",
		  "Add new vaccination":"Ajouter Nouvelle Vaccination",
		  "Add Patient": "Ajouter Patient",
		  "Address": "Adresse",
		  "Administration": "Administration",
		  "Alert Date": "Date d'alerte",
		  "Alert List": "Liste des Alertes",
		  "Alert Note": "Note d'Alerte",
		  "Alerts": "Alertes",
		  "Arrival Date": "Date d'Arrive",
		  "City": "Ville",
		  "Confirm Password": "Confirmer Mot de Passe",
		  "Create Account": "Creer Compte",
		  "Create": "Creer",
		  "Date Administered":"Date de Registration",
		  "Date of Birth": "Date de Naissance",
		  "Date Observed":"Date d'Obeservation",
		  "Date Seen":"Date de visite",
		  "Delete":"Delete",
		  "Emergency Contact Name": "Contact en cas d'Urgence",
		  "Emergency Contact Relationship": "Relation avec le contact",
		  "Father First Name": "Prenom du Pere",
		  "Father Last Name": "Nom du Pere",
		  "Female": "Femelle",
		  "First Name": "Prenom Nom",
		  "Follow Up":"Suivie",
		  "Gender": "Genre",
		  "General Information":"Information Generale",
		  "Hello": "Bonjour",
		  "Last Name": "Nom de Famille",
		  "Login": "Se Connecter",
		  "Logout": "Se Deconnecter",
		  "Male": "Male",
		  "Medical Record ID": "Numero de Numerisation Medicale",
		  "Middle Name": "Surnom",
		  "Mother First Name": "Prenom de la Mere",
		  "Mother Last Name": "Nom de la Mere",
		  "Name":"Nom",
		  "Notes":"Remarques",		
		  "Password": "Mot de Passe",
		  "Patient": "Patient",
		  "Patient Active":"Patient Actif",
		  "Patient ID":"Numero d'Identite du Patient",
		  "Patient List": "Liste des Patients",
		  "Patient Name": "Nom du Patient",
		  "Patient Remarks": "Remarques",
		  "Patients": "Patients",
		  "Reason":"Raison",
		  "Search by Name": "Rechercher par Nom",
		  "Search": "Rechercher",
		  "Severity":"Severite",
		  "Show All": "Afficher tout",
		  "State": "Etat",
		  "Telephone": "Telephone",
		  "Username":"Identifiant",
		  "View":"Regarder",
		  "Zip": "Code Postal"
		  
		  
			}
		return;
	}
	/* */
	
}
		