[Bindable]
public var languageArray:Object;

public function languageInit(str:String):void{
	
	if (str == "ENGLISH"){
		languageArray = {
			"Account Management": "Account Management",
			"Add Alert": "Add Alert",
		  	"Add New Note":"Add New Note",
		  	"Add New Visit":"Add New Visit",
		  	"Add New Allergy":"Add New Allergy",
		  	"Add New Vaccination":"Add New Vaccination",
		  	"Add New Patient":"Add New Patient",
		  	"Add New Prescription":"Add New Prescription",
			"Add Patient": "Add Patient",
			"Add User": "Add User",
			"Address": "Address",
			"Administration": "Administration",
			"Alert Date": "Alert Date",
			"Alert List": "Alert List",
			"Alert Note": "Alert Note",
			"Alerts": "Alerts",
			"Allergies":"Allergies",
			"Allergy List": "Allergy List",
			"Allergy Name": "Allergy Name",
			"Arrival Date": "Arrival Date",
			"City": "City",
			"Conditions":"Conditions",
			"Condition List":"Condition List",
			"Condition Name":"Condition Name",
			"Confirm Password": "Confirm Password",
			"Could not retrieve user list.": "Could not retrieve user list.",
			"Create Account": "Create a New Account",
			"Create": "Create",
			"Created On": "Created On",
			"Date of Birth": "Date of Birth",
		  	"Date Administered":"Date Administered",
		  	"Date Given":"Date Given",
		  	"Date Observed":"Date Observed",		  
		  	"Date Seen":"Date Seen",
		  	"Delete":"Delete",
		  	"Delete Patient":"Delete Patient",
		  	"Doctor Name":"Doctor Name",
		  	"Dosage":"Dosage",
			"Emergency Contact Name": "Emergency Contact Name",
			"Emergency Contact Relationship": "Emergency Contact Relationship",
			"Emergency Contact Number": "Emergency Contact Number",
		  	"Father Name": "Father Name",
			"Father First Name": "Father First Name",
			"Father Last Name": "Father Last Name",
			"Female": "Female",
			"First Name": "First Name",
			"Frequency":"Frequency",
			"Gender": "Gender",
		  	"General Information":"General Information",
			"Hello": "Hello",
			"Last Name": "Last Name",
			"Login": "Login",
			"Logout": "Logout",
			"Male": "Male",
			"Medical Record ID": "Medical Record ID",
			"Medicine Name":"Medicine Name",
			"Middle Name": "Middle Name",
			"Mother Name":"Mother Name",
			"Mother First Name": "Mother First Name",
			"Mother Last Name": "Mother Last Name",
		  	"Name":"Name",
		  	"Note":"Note",
		  	"Note List":"Note List",
		  	"Note Date":"Note Date",
		  	"Notes":"Notes",
			"Password": "Password",
		  	"Patient Active":"Patient Active",
		  	"Patient ID":"Patient ID",
		  	"Patient": "Patient",
			"Patient List": "Patient List",
			"Patient Name": "Patient Name",
			"Patient Remarks": "Patient Remarks",
			"Patients": "Patients",
			"Prescriptions":"Prescriptions",
			"Prescription List":"Prescription List",
			"Reaction":"Reaction",
		  	"Reason":"Reason",
		  	"Refresh Log": "Refresh Log",
		  	"Search by Allergy Name": "Search by Allergy Name",
		  	"Search by Condition Name": "Search by Condition Name",
		  	"Search by Medicine Name":"Search by Medicine Name",
			"Search by Patient Name": "Search by Patient Name",
			"Search by Vaccination Name": "Search by Vaccination Name",
			"Search": "Search",
			"Server Error": "Server Error",
			"Severity":"Severity",
			"Show All": "Show All",
			"State": "State",
			"Telephone": "Telephone",
			"User List": "User List",
			"Username":"Username",
			"Unable to download file.": "Unable to download file.",
			"Vaccination List":"Vaccination List",
			"Vaccination Name":"Vaccination Name",
			"Vaccinations":"Vaccinations",
			"Visits":"Visits",
			"Visits List":"Visits List",
			"Visits-Conditions":"Visits-Conditions",
			"Visit Date":"Visit Date",
			"Visit Type":"Visit Type",
		    "View":"View",
			"Zip": "Zip"
			
		}
	}
	if(str == "FRENCH"){
		languageArray = {
		  "Add Alert": "Ajouter Alerte",
		  "Add New Note":"Ajouter Nouvelle Remarques",
		  "Add New Visit":"Ajouter Nouvelle Visite",
		  "Add New Allergy":"Ajouter Nouvelle Allergie",
		  "Add New Vaccination":"Ajouter Nouvelle Vaccination",
		  "Add New Patient": "Ajouter Nouvelle Patient",
		  "Add New Prescription":"Add New Prescription(French)",
		  "Address": "Adresse",
		  "Administration": "Administration",
		  "Allergies":"Allergies(French)",
		  "Allergy List": "Allergy List(French)",
		  "Allergy Name": "Allergy Name(French)",
		  "Alert Date": "Date d'alerte",
		  "Alert List": "Liste des Alertes",
		  "Alert Note": "Note d'Alerte",
		  "Alerts": "Alertes",
		  "Arrival Date": "Date d'Arrive",
		  "City": "Ville",
		  "Condition Name":"Condition Name(French)",
		  "Confirm Password": "Confirmer Mot de Passe",
		  "Create Account": "Creer Compte",
		  "Create": "Creer",
		  "Date Administered":"Date de Registration",
		  "Date of Birth": "Date de Naissance",
		  "Date Given":"Date Given(French)",
		  "Date Observed":"Date d'Obeservation",
		  "Date Seen":"Date de visite",
		  "Delete":"D'effacement",
		  "Delete Patient":"Patient D'effacement",
		  "Doctor Name":"Doctor Name(French)",
		  "Dosage":"Dosage(French)",
		  "Emergency Contact Name": "Contact en cas d'Urgence",
		  "Emergency Contact Relationship": "Relation avec le contact",
		  "Emergency Contact Number": "Telephone avec le contact",
		  "Father Name": "Nom du Pere",
		  "Father First Name": "Prenom du Pere",
		  "Father Last Name": "Nom du Pere",
		  "Female": "Femelle",
		  "First Name": "Prenom Nom",
		  "Follow Up":"Suivie",
		  "Frequency":"Frequency(French)",
		  "Gender": "Genre",
		  "General Information":"Information Generale",
		  "Hello": "Bonjour",
		  "Last Name": "Nom de Famille",
		  "Login": "Se Connecter",
		  "Logout": "Se Deconnecter",
		  "Male": "Male",
		  "Medical Record ID": "Numero de Numerisation Medicale",
		  "Medicine Name":"Medicine Name(French)",
		  "Middle Name": "Surnom",
		  "Mother Name": "Nom de la Mere",
		  "Mother First Name": "Prenom de la Mere",
		  "Mother Last Name": "Nom de la Mere",
		  "Name":"Nom",
		  "Notes":"Remarques",
		  "Note":"Remarque",
		  "Note Date":"Date de Remarque",
		  "Note List":"Liste des Remarques",		
		  "Password": "Mot de Passe",
		  "Patient": "Patient",
		  "Patient Active":"Patient Actif",
		  "Patient ID":"Numero d'Identite du Patient",
		  "Patient List": "Liste des Patients",
		  "Patient Name": "Nom du Patient",
		  "Patient Remarks": "Remarques",
		  "Patients": "Patients",
		  "Prescription List":"Prescription List(French)",
		  "Prescriptions":"Prescriptions(French)",
		  "Reaction":"Reaction(French)",
		  "Reason":"Raison",
		  "Search by Name": "Rechercher par Nom",
		  "Search by Patient Name": "Rechercher par Nom du Patient",
		  "Search": "Rechercher",
		  "Severity":"Severite",
		  "Show All": "Afficher tout",
		  "State": "Etat",
		  "Telephone": "Telephone",
		  "Username":"Identifiant",
		  "Vaccination List":"Vaccination List(French)",
		  "Vaccination Name":"Vaccination Name(French)",
		  "Vaccinations":"Vaccinations(French)",
		  "View":"Regarder",
		  "Visit Date":"Visit Date(French)",
		  "Visit Type":"Visit Type(French)",
		  "Visits List":"Visits List(French)",
		  "Visits-Conditions":"Visits-Conditions(French)",
		  "Zip": "Code Postal",
		  
		  
		  //to add
		  "Vaccination Name":"Vaccination Name",
		  "Vaccination List":"Vaccination List",
		  "Vaccinations":"Vaccinations",
		  "Dosage":"Dosage",
		  "Frequency":"Frequency",
		  "Date Given":"Date Given",
		  "Medicine Name":"Medicine Name",
		  "Add New Prescription":"Add New Prescription",
		  "Prescription List":"Prescription List",
		  "Prescriptions":"Prescriptions",
		  "Allergies":"Allergies",
		  "Reaction":"Reaction",
		  "Allergy Name": "Allergy Name",
		  "Allergy List": "Allergy List",
		  "Visits List":"Visits List",
		  "Prescriptions":"",
		  "Allergies":"",
		  "Vaccinations":"",
		  "Delete Patient":"",
		  "Visits":"",
		  "Visits-Conditions":"",
		  "Condition Name":"Condition Name",
		  "Visit Date":"Visit Date",
		  "Visit Type":"Visit Type",
		  "Doctor Name":"Doctor Name",
		  "Account Management": "Account Management",
		  "Could not retrieve user list.": "Could not retrieve user list.",
		  "Server Error": "Server Error",
		  "Created On": "Created On",
		  "Add User": "Add User",
		  "User List": "User List",
		  "Refresh Log": "Refresh Log",
		  "Unable to download file.": "Unable to download file."
			}
		return;
	}
	/* */
	
}
		